language: shell

jdk: openjdk14

addons:
  apt:
    packages:
    - fakeroot
    - rpm

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode11.2

install: ci/install.sh

script: ci/script.sh

deploy:
  provider: script
  script: ci/deploy.sh
  skip_cleanup: true
