language: shell

addons:
  apt:
    packages:
    - fakeroot
    - rpm

matrix:
  include:
    - os: linux
    - os: osx

install: ci/install.sh

script: ci/script.sh

deploy:
  provider: script
  script: ci/deploy.sh
